### ISSUE TITLE
react:build failes

### ISSUE THREAD

**Issue by itapai** [lociero/League-of-Legends-Accounts-Creator#58]
I have followed your instructions to build it myself, but the build:react step fails.

```
npm run build:react

> acc-creator-react@1.5.15 build:react
> cross-env NODE_ENV=production webpack --config webpack/renderer.webpack.js --mode production

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
assets by status 2.93 MiB [cached] 2 assets
orphan modules 1020 KiB [orphan] 33 modules
runtime modules 786 bytes 4 modules
modules by path ./node_modules/ 3.44 MiB 353 modules
modules by path ./renderer/ 1020 KiB
  ./renderer/App.jsx + 33 modules 1020 KiB [not cacheable] [built] [code generated]
  ./renderer/css/main.css 39 bytes [built] [code generated] [1 error]
13 modules

ERROR in ./renderer/css/main.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve 'bootswatch/dist/Cosmo/bootstrap.min.css' in '/home/itapai/Development/League-of-Legends-Accounts-Creator/renderer/css'
    at finishWithoutResolve (/home/itapai/Development/League-of-Legends-Accounts-Creator/node_modules/enhanced-resolve/lib/Resolver.js:293:18)
    at /home/itapai/Development/League-of-Legends-Accounts-Creator/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /home/itapai/Development/League-of-Legends-Accounts-Creator/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/home/itapai/Development/League-of-Legends-Accounts-Creator/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/itapai/Development/League-of-Legends-Accounts-Creator/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/home/itapai/Development/League-of-Legends-Accounts-Creator/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/itapai/Development/League-of-Legends-Accounts-Creator/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /home/itapai/Development/League-of-Legends-Accounts-Creator/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/home/itapai/Development/League-of-Legends-Accounts-Creator/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/itapai/Development/League-of-Legends-Accounts-Creator/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at processResult (/home/itapai/Development/League-of-Legends-Accounts-Creator/node_modules/webpack/lib/NormalModule.js:751:19)
    at /home/itapai/Development/League-of-Legends-Accounts-Creator/node_modules/webpack/lib/NormalModule.js:853:5
    at /home/itapai/Development/League-of-Legends-Accounts-Creator/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /home/itapai/Development/League-of-Legends-Accounts-Creator/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/home/itapai/Development/League-of-Legends-Accounts-Creator/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/home/itapai/Development/League-of-Legends-Accounts-Creator/node_modules/css-loader/dist/index.js:155:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 @ ./renderer/App.jsx 9:0-24

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
```

node v18.6.0
 npm v9.6.4

**Comment by lociero** [comment]
@itapai I'm sorry for the late response. I checked it on clean os with node 18.6.0 and it was built successfully. Not really sure why you have problems with bootswatch css it should be installed with initial dependencies install...

**Comment by itapai** [comment]
I tried on another machine, same error. 
You can close this issue if you won't be fixing - I can always just download the release.
